.PHONY: clean All

All:
	@echo "----------Building project:[ CPP - Release ]----------"
	@cd "CPP" && "$(MAKE)" -f  "CPP.mk"
clean:
	@echo "----------Cleaning project:[ CPP - Release ]----------"
	@cd "CPP" && "$(MAKE)" -f  "CPP.mk" clean
